### PR TITLE
fix(groups): wrap text blocks around to fix used bytes not rendering

### PR DESCRIPTION
**Pull request by stiefeljackal**
wrap a text block around used bytes and admin will render the bytes used for first group

### CODE REVIEW

**Comment by stiefeljackal** [comment]
Wrapping the two TextBlock elements with another TextBlock element seemed to have done the trick for some strange reason. See screenshot below (left is compiled and right is 1.7.0):

image

**Comment by GuVAnj8Gv3RJ** [comment]
While this is a fix, I consider it to be invalid XAML. TextBoxes shouldn't be inside each other.

Could you try with <Panel> instead. that's the Avalonia equiv to a rect transform in UIX.

**Comment by stiefeljackal** [comment]
Switched to `<Panel>`; however, this does not fix the situation unfortunately.

image

I could not find any documentation in WPF (since Avalonia is a "successor" to WPF) that suggest `TextBlocks` (not TextBoxes) being stacked into one another would be invalid XAML. I would think `TextBlocks` act like the `span` element in HTML, which is valid to have `span` elements within another `span`.

**Comment by GuVAnj8Gv3RJ** [comment]
Please don't use the WPF docs for Avalonia stuff. 

I'll have to do some playing on my end, I'm not comfortable with text block nesting. It's a design issue, there shoudl be another UI element that works.

**Comment by stiefeljackal** [comment]
Agree that Avalonia docs should be used; however, the Avalonia docs do not provide much information for TextBlock.

I agree that another UI element should be used (or perhaps the entire view for this should be re-examined). Feel free to play around with this PR.

**Comment by GuVAnj8Gv3RJ** [comment]
I played around with the various layout types, Uniform grid should sort this out.

You can find those changes here: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/commit/185f9c4074b89e503740661882df5e55b89b9823

Due to this, I will unfortunately have to close this but I sincerely thank you for your help in this matter. 

@all-contributors please add @stiefeljackal for research.

**Comment by stiefeljackal** [comment]
It's not a problem. I'm very happy that you found the right element for this, and I appreciate you taking the time to look into this. :)

**Pull request closed without merging**
